// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pugling.Api.Data;

#nullable disable

namespace Pugling.Api.Data.Migrations
{
    [DbContext(typeof(PuglingDbContext))]
    [Migration("20260712175749_PerformanceIndexesHotPaths")]
    partial class PerformanceIndexesHotPaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Pugling.Api.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Pugling.Api.Models.AccountProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FatherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChildId");

                    b.HasIndex("FatherId");

                    b.HasIndex("Role", "ChildId")
                        .IsUnique()
                        .HasFilter("[ChildId] IS NOT NULL");

                    b.HasIndex("Role", "FatherId")
                        .IsUnique()
                        .HasFilter("[FatherId] IS NOT NULL");

                    b.ToTable("AccountProfiles");
                });

            modelBuilder.Entity("Pugling.Api.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Threshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Pugling.Api.Models.AchievementAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId")
                        .IsUnique();

                    b.ToTable("AchievementAwards");
                });

            modelBuilder.Entity("Pugling.Api.Models.ActivationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopArticleId");

                    b.HasIndex("ChildId", "SupervisorId");

                    b.ToTable("ActivationRequests");
                });

            modelBuilder.Entity("Pugling.Api.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Pugling.Api.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedSkins")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedSkin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Pugling.Api.Models.ChildInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShopArticleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopArticleId");

                    b.HasIndex("ChildId", "ShopArticleId")
                        .IsUnique();

                    b.ToTable("ChildInventories");
                });

            modelBuilder.Entity("Pugling.Api.Models.ChildPointsEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "Kind");

                    b.HasIndex("ChildId", "CreatedAt", "Id");

                    b.ToTable("ChildPoints");
                });

            modelBuilder.Entity("Pugling.Api.Models.ClozeText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gaps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .HasColumnType("TEXT");

                    b.Property<string>("WordBank")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ClozeTexts");
                });

            modelBuilder.Entity("Pugling.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorFatherId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultRequireTypedTest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultStage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultUseLeitner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GradeMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GradeMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolTypes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedBonus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorFatherId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Pugling.Api.Models.ExerciseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Name")
                        .IsUnique();

                    b.ToTable("ExerciseCategories");
                });

            modelBuilder.Entity("Pugling.Api.Models.ExerciseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("ExerciseId", "OrderIndex");

                    b.ToTable("ExerciseItems");
                });

            modelBuilder.Entity("Pugling.Api.Models.ExerciseTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaggedByRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TagId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("ExerciseTags");
                });

            modelBuilder.Entity("Pugling.Api.Models.Father", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fathers");
                });

            modelBuilder.Entity("Pugling.Api.Models.ItemProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Box")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("IntroducedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAnswerAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MasteryPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ChildId", "ExerciseId");

                    b.HasIndex("ChildId", "ItemId")
                        .IsUnique();

                    b.HasIndex("ChildId", "VocabularyId");

                    b.ToTable("ItemProgress");
                });

            modelBuilder.Entity("Pugling.Api.Models.ItemReviewEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenAnswer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlanPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ChildId", "VocabularyId");

                    b.HasIndex("ChildId", "ItemId", "At");

                    b.ToTable("ItemReviewEvents");
                });

            modelBuilder.Entity("Pugling.Api.Models.KeyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("KeyResults");
                });

            modelBuilder.Entity("Pugling.Api.Models.Klassenarbeit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeComment")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Klassenarbeiten");
                });

            modelBuilder.Entity("Pugling.Api.Models.KlassenarbeitExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlassenarbeitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("KlassenarbeitId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("KlassenarbeitExercises");
                });

            modelBuilder.Entity("Pugling.Api.Models.KlassenarbeitTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlassenarbeitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("KlassenarbeitId", "TagId")
                        .IsUnique();

                    b.ToTable("KlassenarbeitTags");
                });

            modelBuilder.Entity("Pugling.Api.Models.LearnGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("LearnGoals");
                });

            modelBuilder.Entity("Pugling.Api.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("Pugling.Api.Models.MissionAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId", "PeriodKey")
                        .IsUnique();

                    b.ToTable("MissionAwards");
                });

            modelBuilder.Entity("Pugling.Api.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivation")
                        .HasColumnType("TEXT");

                    b.Property<int>("RewardOnComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardPerKeyResult")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Pugling.Api.Models.ObjectiveReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId", "PeriodKey")
                        .IsUnique();

                    b.ToTable("ObjectiveRewards");
                });

            modelBuilder.Entity("Pugling.Api.Models.PlanPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoxIntervalDays")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cadence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComboBonusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComboThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoalThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBox")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewContentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PenaltyCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsGoalMet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireTypedTest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedBonusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedThresholdSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageSchedule")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLeitner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("StudyPlanId", "Order", "Id");

                    b.ToTable("PlanPositions");
                });

            modelBuilder.Entity("Pugling.Api.Models.PositionGoalPenalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanPositionId", "PeriodKey")
                        .IsUnique();

                    b.ToTable("PositionGoalPenalties");
                });

            modelBuilder.Entity("Pugling.Api.Models.PositionGoalReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanPositionId", "PeriodKey")
                        .IsUnique();

                    b.ToTable("PositionGoalRewards");
                });

            modelBuilder.Entity("Pugling.Api.Models.PositionItemProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Box")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("IntroducedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanPositionId", "ItemIndex")
                        .IsUnique();

                    b.ToTable("PositionItemProgress");
                });

            modelBuilder.Entity("Pugling.Api.Models.PracticeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cursor")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlanPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyPlanId", "Day");

                    b.HasIndex("PlanPositionId", "Day", "Mode");

                    b.ToTable("PracticeSessions");
                });

            modelBuilder.Entity("Pugling.Api.Models.ReviewEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PracticeSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSessionId");

                    b.ToTable("ReviewEvents");
                });

            modelBuilder.Entity("Pugling.Api.Models.ShopArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FatherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FatherId", "ArticleNumber")
                        .IsUnique();

                    b.ToTable("ShopArticles");
                });

            modelBuilder.Entity("Pugling.Api.Models.ShopListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GemPrice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRefilledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RefillAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RefillDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefillKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShopArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitsPerPurchase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopArticleId");

                    b.ToTable("ShopListings");
                });

            modelBuilder.Entity("Pugling.Api.Models.ShopPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GemPrice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShopListingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitsPerPurchase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopListingId");

                    b.HasIndex("ChildId", "SupervisorId");

                    b.ToTable("ShopPurchases");
                });

            modelBuilder.Entity("Pugling.Api.Models.StudyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("Pugling.Api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Pugling.Api.Models.SupervisorLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId", "StudentId")
                        .IsUnique();

                    b.ToTable("SupervisorLinks");
                });

            modelBuilder.Entity("Pugling.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Pugling.Api.Models.TestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cursor")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Graded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlanPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScorePercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyPlanId", "Day");

                    b.HasIndex("PlanPositionId", "Day", "CompletedAt", "Passed");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("Pugling.Api.Models.TestItemResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenAnswer")
                        .HasColumnType("TEXT");

                    b.Property<int>("HintsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestAttemptId");

                    b.ToTable("TestItemResults");
                });

            modelBuilder.Entity("Pugling.Api.Models.TimeSlotRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("Pugling.Api.Models.TimetableEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeOfDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ChildId", "SubjectId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("Timetable");
                });

            modelBuilder.Entity("Pugling.Api.Models.VocabTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VocabTags");
                });

            modelBuilder.Entity("Pugling.Api.Models.VocabTagLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("VocabTagId", "VocabularyId")
                        .IsUnique();

                    b.ToTable("VocabTagLinks");
                });

            modelBuilder.Entity("Pugling.Api.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseFormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseFormRelation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Noun")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartOfSpeech")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PronunciationAudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Verb")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseFormId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Vocabulary");
                });

            modelBuilder.Entity("Pugling.Api.Models.VocabularyTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaggedByRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("TagId", "VocabularyId")
                        .IsUnique();

                    b.ToTable("VocabularyTags");
                });

            modelBuilder.Entity("Pugling.Api.Models.AccountProfile", b =>
                {
                    b.HasOne("Pugling.Api.Models.Account", "Account")
                        .WithMany("Profiles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pugling.Api.Models.Father", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("Child");

                    b.Navigation("Father");
                });

            modelBuilder.Entity("Pugling.Api.Models.Achievement", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Pugling.Api.Models.AchievementAward", b =>
                {
                    b.HasOne("Pugling.Api.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("Pugling.Api.Models.ActivationRequest", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.ShopArticle", "ShopArticle")
                        .WithMany()
                        .HasForeignKey("ShopArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("ShopArticle");
                });

            modelBuilder.Entity("Pugling.Api.Models.Chapter", b =>
                {
                    b.HasOne("Pugling.Api.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Pugling.Api.Models.ChildInventory", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.ShopArticle", "ShopArticle")
                        .WithMany()
                        .HasForeignKey("ShopArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ShopArticle");
                });

            modelBuilder.Entity("Pugling.Api.Models.ChildPointsEntry", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany("PointsEntries")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Pugling.Api.Models.Exercise", b =>
                {
                    b.HasOne("Pugling.Api.Models.Father", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorFatherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pugling.Api.Models.ExerciseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pugling.Api.Models.Chapter", "Chapter")
                        .WithMany("Exercises")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Pugling.Api.Models.ExerciseCategory", b =>
                {
                    b.HasOne("Pugling.Api.Models.Subject", "Subject")
                        .WithMany("Categories")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Pugling.Api.Models.ExerciseItem", b =>
                {
                    b.HasOne("Pugling.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Vocabulary", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Pugling.Api.Models.ExerciseTag", b =>
                {
                    b.HasOne("Pugling.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Tag", "Tag")
                        .WithMany("ExerciseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Pugling.Api.Models.ItemProgress", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.ExerciseItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Pugling.Api.Models.ItemReviewEvent", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.ExerciseItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Pugling.Api.Models.KeyResult", b =>
                {
                    b.HasOne("Pugling.Api.Models.Objective", "Objective")
                        .WithMany("KeyResults")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Pugling.Api.Models.Klassenarbeit", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Pugling.Api.Models.KlassenarbeitExercise", b =>
                {
                    b.HasOne("Pugling.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Klassenarbeit", "Klassenarbeit")
                        .WithMany("Exercises")
                        .HasForeignKey("KlassenarbeitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Klassenarbeit");
                });

            modelBuilder.Entity("Pugling.Api.Models.KlassenarbeitTag", b =>
                {
                    b.HasOne("Pugling.Api.Models.Klassenarbeit", "Klassenarbeit")
                        .WithMany("Tags")
                        .HasForeignKey("KlassenarbeitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klassenarbeit");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Pugling.Api.Models.LearnGoal", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Pugling.Api.Models.Mission", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Pugling.Api.Models.MissionAward", b =>
                {
                    b.HasOne("Pugling.Api.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Pugling.Api.Models.Objective", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Pugling.Api.Models.ObjectiveReward", b =>
                {
                    b.HasOne("Pugling.Api.Models.Objective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Pugling.Api.Models.PlanPosition", b =>
                {
                    b.HasOne("Pugling.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.StudyPlan", "StudyPlan")
                        .WithMany("Positions")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("Pugling.Api.Models.PositionGoalPenalty", b =>
                {
                    b.HasOne("Pugling.Api.Models.PlanPosition", "PlanPosition")
                        .WithMany()
                        .HasForeignKey("PlanPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPosition");
                });

            modelBuilder.Entity("Pugling.Api.Models.PositionGoalReward", b =>
                {
                    b.HasOne("Pugling.Api.Models.PlanPosition", "PlanPosition")
                        .WithMany()
                        .HasForeignKey("PlanPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPosition");
                });

            modelBuilder.Entity("Pugling.Api.Models.PositionItemProgress", b =>
                {
                    b.HasOne("Pugling.Api.Models.PlanPosition", "PlanPosition")
                        .WithMany("ItemProgress")
                        .HasForeignKey("PlanPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPosition");
                });

            modelBuilder.Entity("Pugling.Api.Models.PracticeSession", b =>
                {
                    b.HasOne("Pugling.Api.Models.PlanPosition", "PlanPosition")
                        .WithMany()
                        .HasForeignKey("PlanPositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pugling.Api.Models.StudyPlan", "StudyPlan")
                        .WithMany()
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPosition");

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("Pugling.Api.Models.ReviewEvent", b =>
                {
                    b.HasOne("Pugling.Api.Models.PracticeSession", "PracticeSession")
                        .WithMany("Reviews")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeSession");
                });

            modelBuilder.Entity("Pugling.Api.Models.ShopArticle", b =>
                {
                    b.HasOne("Pugling.Api.Models.Father", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Father");
                });

            modelBuilder.Entity("Pugling.Api.Models.ShopListing", b =>
                {
                    b.HasOne("Pugling.Api.Models.ShopArticle", "ShopArticle")
                        .WithMany("Listings")
                        .HasForeignKey("ShopArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopArticle");
                });

            modelBuilder.Entity("Pugling.Api.Models.ShopPurchase", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.ShopListing", "ShopListing")
                        .WithMany()
                        .HasForeignKey("ShopListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("ShopListing");
                });

            modelBuilder.Entity("Pugling.Api.Models.StudyPlan", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Pugling.Api.Models.SupervisorLink", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Student")
                        .WithMany("SupervisorLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Father", "Supervisor")
                        .WithMany("SupervisedLinks")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Pugling.Api.Models.Tag", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Pugling.Api.Models.TestAttempt", b =>
                {
                    b.HasOne("Pugling.Api.Models.PlanPosition", "PlanPosition")
                        .WithMany()
                        .HasForeignKey("PlanPositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pugling.Api.Models.StudyPlan", "StudyPlan")
                        .WithMany()
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPosition");

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("Pugling.Api.Models.TestItemResult", b =>
                {
                    b.HasOne("Pugling.Api.Models.TestAttempt", "TestAttempt")
                        .WithMany("Results")
                        .HasForeignKey("TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("Pugling.Api.Models.TimetableEntry", b =>
                {
                    b.HasOne("Pugling.Api.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Pugling.Api.Models.VocabTagLink", b =>
                {
                    b.HasOne("Pugling.Api.Models.VocabTag", "VocabTag")
                        .WithMany("Links")
                        .HasForeignKey("VocabTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Vocabulary", "Vocabulary")
                        .WithMany("TagLinks")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabTag");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Pugling.Api.Models.Vocabulary", b =>
                {
                    b.HasOne("Pugling.Api.Models.Vocabulary", "BaseForm")
                        .WithMany()
                        .HasForeignKey("BaseFormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseForm");
                });

            modelBuilder.Entity("Pugling.Api.Models.VocabularyTag", b =>
                {
                    b.HasOne("Pugling.Api.Models.Tag", "Tag")
                        .WithMany("VocabularyTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pugling.Api.Models.Vocabulary", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Pugling.Api.Models.Account", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Pugling.Api.Models.Chapter", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Pugling.Api.Models.Child", b =>
                {
                    b.Navigation("PointsEntries");

                    b.Navigation("SupervisorLinks");
                });

            modelBuilder.Entity("Pugling.Api.Models.Father", b =>
                {
                    b.Navigation("SupervisedLinks");
                });

            modelBuilder.Entity("Pugling.Api.Models.Klassenarbeit", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Pugling.Api.Models.Objective", b =>
                {
                    b.Navigation("KeyResults");
                });

            modelBuilder.Entity("Pugling.Api.Models.PlanPosition", b =>
                {
                    b.Navigation("ItemProgress");
                });

            modelBuilder.Entity("Pugling.Api.Models.PracticeSession", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Pugling.Api.Models.ShopArticle", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Pugling.Api.Models.StudyPlan", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Pugling.Api.Models.Subject", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Pugling.Api.Models.Tag", b =>
                {
                    b.Navigation("ExerciseTags");

                    b.Navigation("VocabularyTags");
                });

            modelBuilder.Entity("Pugling.Api.Models.TestAttempt", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Pugling.Api.Models.VocabTag", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Pugling.Api.Models.Vocabulary", b =>
                {
                    b.Navigation("TagLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
