#!/usr/bin/env node

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const defaultInput = 'http://localhost:5200/openapi/v1.json';
const defaultOutput = 'tools/bruno/Pugling.Api';
const generatedMarker = '.pugling-generated';

const args = parseArgs(process.argv.slice(2));
const input = args.input ?? args.i ?? defaultInput;
const output = args.output ?? args.o ?? defaultOutput;
const force = args.force === true;

const knownVariables = new Map([
  ['fatherId', '1'],
  ['childId', '1'],
  ['fatherPin', '0000'],
  ['childPin', '1111'],
  ['subjectId', '1'],
  ['chapterId', '1'],
  ['categoryId', '1'],
  ['exerciseId', '1'],
  ['planId', '1'],
  ['positionId', '1'],
  ['sessionId', '1'],
  ['attemptId', '1'],
  ['tagId', '1'],
  ['classTestId', '1'],
  ['missionId', '1'],
  ['achievementId', '1'],
  ['rewardId', '1'],
  ['redemptionId', '1'],
  ['articleId', '1'],
  ['listingId', '1'],
  ['purchaseId', '1'],
  ['activationId', '1'],
  ['vocabularyId', '1'],
  ['wordId', '1'],
  ['skinId', 'classic'],
  ['date', new Date().toISOString().slice(0, 10)],
]);
const discoveredVariables = new Set(knownVariables.keys());

const resourceIdBySegment = new Map([
  ['fathers', 'fatherId'],
  ['children', 'childId'],
  ['subjects', 'subjectId'],
  ['chapters', 'chapterId'],
  ['categories', 'categoryId'],
  ['exercises', 'exerciseId'],
  ['study-plans', 'planId'],
  ['positions', 'positionId'],
  ['practice-sessions', 'sessionId'],
  ['tests', 'attemptId'],
  ['class-tests', 'classTestId'],
  ['tags', 'tagId'],
  ['missions', 'missionId'],
  ['achievements', 'achievementId'],
  ['rewards', 'rewardId'],
  ['redemptions', 'redemptionId'],
  ['articles', 'articleId'],
  ['listings', 'listingId'],
  ['purchases', 'purchaseId'],
  ['activations', 'activationId'],
  ['vocabulary', 'vocabularyId'],
  ['words', 'wordId'],
  ['skins', 'skinId'],
]);

const openApi = await loadOpenApi(input);
await prepareOutput(output, force);
await writeCollectionFiles(openApi, output);

console.log(`Bruno-Collection erzeugt: ${output}`);

function parseArgs(values) {
  const result = {};

  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];

    if (!value.startsWith('--')) {
      if (!result.input) result.input = value;
      continue;
    }

    const [rawName, inlineValue] = value.slice(2).split('=', 2);
    const name = rawName.length === 1 ? rawName : rawName.replaceAll('-', '');

    if (inlineValue !== undefined) {
      result[name] = inlineValue;
      continue;
    }

    if (name === 'force') {
      result[name] = true;
      continue;
    }

    result[name] = values[index + 1];
    index += 1;
  }

  return result;
}

async function loadOpenApi(source) {
  if (/^https?:\/\//i.test(source)) {
    const response = await fetch(source);
    if (!response.ok) throw new Error(`OpenAPI konnte nicht geladen werden: ${response.status} ${response.statusText}`);
    return response.json();
  }

  return JSON.parse(await readFile(source, 'utf8'));
}

async function prepareOutput(directory, forceOutput) {
  const markerPath = path.join(directory, generatedMarker);

  try {
    await readFile(markerPath, 'utf8');
    await rm(directory, { recursive: true, force: true });
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;

    if (forceOutput) {
      await rm(directory, { recursive: true, force: true });
    }
  }

  await mkdir(directory, { recursive: true });
  await writeFile(markerPath, 'Generated by tools/bruno/generate-bruno.mjs. Do not edit generated request files by hand.\n');
}

async function writeCollectionFiles(api, directory) {
  const collectionMeta = {
    version: '1',
    name: 'Pugling API',
    type: 'collection',
    auth: {
      mode: 'bearer',
      bearer: { token: '{{token}}' },
    },
  };
  await writeFile(path.join(directory, 'bruno.json'), `${JSON.stringify(collectionMeta, null, 2)}\n`);
  await writeFile(path.join(directory, 'README.md'), collectionReadme());

  const operations = collectOperations(api);

  const environmentDir = path.join(directory, 'environments');
  await mkdir(environmentDir, { recursive: true });
  await writeFile(path.join(environmentDir, 'local.bru'), localEnvironment());

  for (const [index, operation] of operations.entries()) {
    const folder = sanitizePathPart(operation.tag);
    const fileName = `${String(index + 1).padStart(3, '0')}-${sanitizePathPart(operation.name)}.bru`;
    const targetDir = path.join(directory, folder);

    await mkdir(targetDir, { recursive: true });
    await writeFile(path.join(targetDir, fileName), renderOperation(operation, index + 1));
  }
}

function collectOperations(api) {
  const methods = new Set(['get', 'post', 'put', 'patch', 'delete', 'head', 'options']);
  const operations = [];

  for (const [apiPath, pathItem] of Object.entries(api.paths ?? {})) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!methods.has(method)) continue;

      for (const parameterName of collectPathParameters(apiPath)) discoveredVariables.add(toVariableName(parameterName));
      for (const parameter of collectQueryParameters(pathItem, operation)) discoveredVariables.add(toVariableName(parameter.name));

      const tag = operation.tags?.[0] ?? firstPathSegment(apiPath) ?? 'API';
      operations.push({
        method,
        path: apiPath,
        tag,
        name: operation.summary?.trim() || `${method.toUpperCase()} ${apiPath}`,
        operation,
        pathParameters: collectPathParameters(apiPath),
        queryParameters: collectQueryParameters(pathItem, operation),
        body: sampleBody(api, operation),
        isAuthEndpoint: isAuthEndpoint(apiPath),
        captureVariables: captureVariablesFor(apiPath),
      });
    }
  }

  return operations.sort((left, right) => `${left.tag} ${left.path} ${left.method}`.localeCompare(`${right.tag} ${right.path} ${right.method}`));
}

function renderOperation(operation, sequence) {
  const url = `{{baseUrl}}${replacePathVariables(operation.path)}`;
  const sections = [
    `meta {\n  name: ${escapeBruValue(operation.name)}\n  type: http\n  seq: ${sequence}\n  tags: [\n    ${escapeBruValue(operation.tag)}\n  ]\n}`,
    `${operation.method} {\n  url: ${url}\n}`,
  ];

  if (operation.queryParameters.length > 0) {
    sections.push(`params:query {\n${operation.queryParameters.map(parameter => `  ${parameter.name}: ${queryValue(parameter)}`).join('\n')}\n}`);
  }

  const headers = ['  Accept: application/json'];
  if (operation.body !== undefined) headers.push('  Content-Type: application/json');
  sections.push(`headers {\n${headers.join('\n')}\n}`);

  if (!operation.isAuthEndpoint) {
    sections.push(`auth {\n  mode: inherit\n}`);
  }

  if (operation.body !== undefined) {
    sections.push(`body {\n${indent(JSON.stringify(operation.body, null, 2), 2)}\n}`);
  }

  const postScript = postResponseScript(operation);
  if (postScript) sections.push(`script:post-response {\n${indent(postScript, 2)}\n}`);

  return `${sections.join('\n\n')}\n`;
}

function collectPathParameters(apiPath) {
  return [...apiPath.matchAll(/\{([^}:]+)(?::[^}]+)?\}/g)].map(match => match[1]);
}

function collectQueryParameters(pathItem, operation) {
  return [...(pathItem.parameters ?? []), ...(operation.parameters ?? [])]
    .filter(parameter => parameter.in === 'query')
    .map(parameter => ({ name: parameter.name, schema: parameter.schema ?? {} }));
}

function replacePathVariables(apiPath) {
  return apiPath.replace(/\{([^}:]+)(?::[^}]+)?\}/g, (_, name) => `{{${toVariableName(name)}}}`);
}

function queryValue(parameter) {
  const variableName = toVariableName(parameter.name);
  if (knownVariables.has(variableName)) return `{{${variableName}}}`;

  if (parameter.schema?.type === 'boolean') return 'true';
  if (parameter.schema?.type === 'integer' || parameter.schema?.type === 'number') return '1';
  if (parameter.schema?.format === 'date') return '{{date}}';

  return `{{${variableName}}}`;
}

function isAuthEndpoint(apiPath) {
  return apiPath.startsWith('/api/v1/auth/father') || apiPath.startsWith('/api/v1/auth/child');
}

function sampleBody(api, operation) {
  const jsonContent = operation.requestBody?.content?.['application/json'];
  if (!jsonContent) return undefined;

  const explicitExample = jsonContent.example ?? firstExampleValue(jsonContent.examples);
  if (explicitExample !== undefined) return substituteVariables(explicitExample);

  const schema = resolveSchema(api, jsonContent.schema);
  if (!schema) return {};

  return substituteVariables(sampleFromSchema(api, schema));
}

function firstExampleValue(examples) {
  const first = Object.values(examples ?? {})[0];
  return first?.value;
}

function sampleFromSchema(api, schema) {
  if (schema.example !== undefined) return schema.example;
  if (schema.default !== undefined) return schema.default;
  if (schema.enum?.length) return schema.enum[0];
  if (schema.oneOf?.length) return sampleFromSchema(api, resolveSchema(api, schema.oneOf[0]) ?? schema.oneOf[0]);
  if (schema.anyOf?.length) return sampleFromSchema(api, resolveSchema(api, schema.anyOf[0]) ?? schema.anyOf[0]);
  if (schema.allOf?.length) return Object.assign({}, ...schema.allOf.map(item => sampleFromSchema(api, resolveSchema(api, item) ?? item)));

  if (schema.type === 'array') return [sampleFromSchema(api, resolveSchema(api, schema.items) ?? schema.items ?? { type: 'string' })];
  if (schema.type === 'object' || schema.properties) {
    const result = {};
    for (const [name, property] of Object.entries(schema.properties ?? {})) {
      result[name] = valueForProperty(api, name, resolveSchema(api, property) ?? property);
    }
    return result;
  }

  return primitiveSample(schema.type, schema.format);
}

function valueForProperty(api, name, schema) {
  const variableName = toVariableName(name);
  if (knownVariables.has(variableName)) return `{{${variableName}}}`;
  if (name.toLowerCase() === 'pin') return '{{fatherPin}}';
  if (schema.format === 'date') return '{{date}}';
  return sampleFromSchema(api, schema);
}

function primitiveSample(type, format) {
  if (format === 'date') return '{{date}}';
  if (format === 'date-time') return new Date().toISOString();
  if (type === 'integer' || type === 'number') return 1;
  if (type === 'boolean') return true;
  return 'string';
}

function resolveSchema(api, schema) {
  if (!schema?.$ref) return schema;

  const pathParts = schema.$ref.replace(/^#\//, '').split('/').map(part => part.replaceAll('~1', '/').replaceAll('~0', '~'));
  return pathParts.reduce((current, part) => current?.[part], api);
}

function substituteVariables(value) {
  if (Array.isArray(value)) return value.map(substituteVariables);
  if (value && typeof value === 'object') {
    const loginPin = value.childId !== undefined ? '{{childPin}}' : value.fatherId !== undefined ? '{{fatherPin}}' : undefined;
    return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, substituteVariablesForKey(key, entry, loginPin)]));
  }
  return value;
}

function substituteVariablesForKey(key, value, loginPin) {
  const variableName = toVariableName(key);
  if (knownVariables.has(variableName)) return `{{${variableName}}}`;
  if (key.toLowerCase() === 'pin') return loginPin ?? '{{fatherPin}}';
  return substituteVariables(value);
}

function captureVariablesFor(apiPath) {
  if (apiPath === '/api/v1/auth/father') return ['token', 'fatherId'];
  if (apiPath === '/api/v1/auth/child') return ['token', 'childId'];

  const variables = new Set(collectPathParameters(apiPath).map(toVariableName));
  for (const segment of apiPath.split('/').filter(Boolean).reverse()) {
    if (resourceIdBySegment.has(segment)) {
      variables.add(resourceIdBySegment.get(segment));
      break;
    }
  }

  return [...variables];
}

function postResponseScript(operation) {
  if (operation.isAuthEndpoint) {
    return `var jsonData = res.getBody();\nbru.setEnvVar('token', jsonData.token);`;
  }

  const variables = operation.captureVariables;
  const mappings = variables.map(variable =>
    `capture('${variable}', body.${responsePropertyFor(variable)} ?? body.id);`
  );

  const genericCaptures = [...knownVariables.keys()]
    .filter(variable => variable.endsWith('Id'))
    .map(variable => `capture('${variable}', body.${responsePropertyFor(variable)});`);

  const bodyLines = [...new Set([...mappings, ...genericCaptures])].join('\n');
  if (!bodyLines) return '';

  return `const body = res.getBody();\n\nfunction capture(name, value) {\n  if (value === undefined || value === null || value === '') return;\n  bru.setVar(name, value);\n  bru.setEnvVar(name, String(value), { persist: true });\n}\n\nif (body && typeof body === 'object' && !Array.isArray(body)) {\n${indent(bodyLines, 2)}\n}`;
}

function responsePropertyFor(variableName) {
  return variableName.replace(/Id$/, 'Id');
}

function localEnvironment() {
  const variables = new Map([
    ...knownVariables.entries(),
    ...[...discoveredVariables].sort().map(variable => [variable, defaultValueFor(variable)]),
  ]);
  const vars = [
    ['baseUrl', 'http://localhost:5200'],
    ['token', ''],
    ...variables.entries(),
  ];

  return `vars {\n${vars.map(([key, value]) => `  ${key}: ${value}`).join('\n')}\n}\n`;
}

function defaultValueFor(variableName) {
  if (knownVariables.has(variableName)) return knownVariables.get(variableName);
  if (variableName.endsWith('Id')) return '1';
  if (variableName.toLowerCase().includes('date')) return '{{date}}';
  if (variableName.toLowerCase().includes('active')) return 'true';
  return '';
}

function collectionReadme() {
  return `# Pugling API Bruno Collection\n\nDiese Collection ist generiert. Manuelle Änderungen an Requests gehen beim nächsten Export verloren.\n\n## Aktualisieren\n\n\`npm run bruno:generate\`\n\nStandardquelle ist \`http://localhost:5200/openapi/v1.json\`. Alternativ kann eine gespeicherte OpenAPI-Datei genutzt werden:\n\n\`node tools/bruno/generate-bruno.mjs --input ./openapi.json --output tools/bruno/Pugling.Api\`\n\n## Auth\n\nDie Collection ist mit Bearer-Token-Auth konfiguriert (\`{{token}}\`). Vor dem Testen einen Login-Request ausführen – der Post-Response-Script setzt \`token\` automatisch ins aktive Environment. Alle anderen Requests erben die Auth von der Collection.\n\n## Variablen\n\nPfad- und Body-Werte werden als Bruno-Variablen gesetzt, z. B. \`{{fatherId}}\`, \`{{childId}}\`, \`{{planId}}\`, \`{{positionId}}\`.\n`;
}

function firstPathSegment(apiPath) {
  return apiPath.split('/').filter(Boolean).at(2);
}

function toVariableName(name) {
  return name.replace(/[^a-zA-Z0-9]+(.)/g, (_, character) => character.toUpperCase());
}

function sanitizePathPart(value) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'request';
}

function escapeBruValue(value) {
  return String(value).replace(/[\r\n]/g, ' ').trim();
}

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces);
  return String(value).split('\n').map(line => `${prefix}${line}`).join('\n');
}