name: local
variables:
  - name: baseUrl
    value: http://localhost:5200
  - name: token
    value: ""
  - name: fatherId
    value: "4"
  - name: childId
    value: "3"
  - name: fatherPin
    value: "0000"
  - name: childPin
    value: "1111"
  - name: subjectId
    value: "1"
  - name: chapterId
    value: "1"
  - name: categoryId
    value: "1"
  - name: exerciseId
    value: "1"
  - name: planId
    value: "1"
  - name: positionId
    value: "1"
  - name: sessionId
    value: "1"
  - name: attemptId
    value: "1"
  - name: tagId
    value: "1"
  - name: classTestId
    value: "1"
  - name: missionId
    value: "1"
  - name: achievementId
    value: "1"
  - name: rewardId
    value: "1"
  - name: redemptionId
    value: "1"
  - name: articleId
    value: "7"
  - name: listingId
    value: "7"
  - name: purchaseId
    value: "1"
  - name: activationId
    value: "1"
  - name: vocabularyId
    value: "1"
  - name: wordId
    value: "1"
  - name: skinId
    value: classic
  - name: date
    value: 2026-07-07
  - name: entryId
    value: "1"
  - name: id
    value: ""
  - name: key
    value: ""
  - name: requestId
    value: "1"
  - name: sentenceId
    value: "1"
  - name: type
    value: ""
